import type { Metadata } from "next";
import Link from "next/link";
import { GuideCards, GuideShell } from "./guide-shell";

export const metadata: Metadata = { title: "PriceAI 快速入门：如何比价、判断渠道、申请收录和反馈问题 | PriceAI" };

const toc = [{ id: "about", label: "PriceAI 是什么" }, { id: "use-priceai", label: "你可以怎么用 PriceAI" }, { id: "verify", label: "购买前先核验" }, { id: "contribute", label: "参与完善 PriceAI" }, { id: "next-reading", label: "继续阅读" }];

export default function GuidesPage() {
  return <GuideShell toc={toc}><h1>快速入门</h1><p className="lead">第一次使用 PriceAI，先了解它能做什么，以及如何判断不同渠道的价格和风险。</p><h2 id="about">PriceAI 是什么</h2><p>PriceAI 是一个 AI 订阅和模型 API 的比价工具。它把不同渠道里的价格、库存、来源、原始商品标题和更新时间整理到一起，帮助你先完成比较，再决定是否跳转到原渠道购买。</p><aside className="priceai-doc-callout info"><b>●　先记住一件事</b><p>PriceAI 是信息聚合工具，不是卖家背书。看到低价时，先看来源、交付方式、库存、更新时间和售后入口。</p></aside><h2 id="use-priceai">你可以怎么用 PriceAI</h2><GuideCards items={[{ href: "/channels", title: "查第三方订阅渠道", text: "比较 ChatGPT、Claude、Gemini、Grok 等卡网渠道的价格、来源、库存和更新时间。" }, { href: "/official-prices", title: "看官方订阅地区价", text: "了解官网价、地区价、支付方式、税费、汇率和账户地区，再判断是否适合自己。" }, { href: "/official-api", title: "看官方 API", text: "比较供应商、模型、计价方式和额度，先确认 API 适不适合自己的调用场景。" }]} /><h2 id="verify">购买前先核验</h2><p>跳转原渠道前，建议按下面的顺序快速核验：</p><ol><li>打开商品详情，看原始渠道、原始商品名、库存、更新时间和购买链接。</li><li>查看商品描述、售后入口、联系方式和平台投诉入口。</li><li>金额较大时，先联系卖家确认交付方式、有效期和退款边界，再决定是否交易。</li></ol><aside className="priceai-doc-callout warning"><b>▲　不要只看最低价</b><p>最低价可能对应不同的账号、交付方式、有效期或售后条件。价格差异本身不是结论，来源和限制条件才是。</p></aside><h2 id="contribute">参与完善 PriceAI</h2><GuideCards items={[{ href: "/submit", title: "申请收录自营店铺", text: "提交店铺和商品信息，符合条件的渠道会进入集中审核。" }, { href: "/channels", title: "举报问题商品", text: "发现价格、链接、描述或渠道异常时，可以从商品详情页反馈。" }, { href: "/support", title: "提交平台建议", text: "对功能、分类或使用体验有建议，可以直接反馈给我们。" }]} /><h2 id="next-reading">继续阅读</h2><GuideCards items={[{ href: "/guides/why-ai-subscription-prices-differ", title: "AI 订阅价格为什么差很多", text: "先理解官网正价、地区价、资格价、代充价和第三方渠道价。" }, { href: "/guides/are-ai-subscription-card-shops-reliable", title: "卡网渠道靠谱吗", text: "把卡网理解成信息源和交易入口，学习购买前的核验清单。" }, { href: "/guides/how-to-subscribe-ai-officially", title: "如何自己完成官方订阅", text: "从官网、App Store、Google Play、支付方式和售后入口理解官方路径。" }, { href: "/guides/chatgpt-subscription-options", title: "ChatGPT 获取方式", text: "区分 Plus、Pro、Team、成品号、代充和卡密。" }]} /><p>也可以从左侧目录选择对应分类，或者使用顶部的搜索快速定位内容。<Link href="/">返回 PriceAI 主站</Link>。</p></GuideShell>;
}
