import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "赞助位合作 | PriceAI" };

const benefits = [["品牌曝光", "让正在比较 AI 订阅、API 和中转服务的用户看到你的服务名称、定位和入口。"], ["活动引流", "承接优惠码、首充活动、新品发布或限时说明，把用户带回你的官网或活动页确认规则。"], ["资料承接", "把官网、定价页、监测页、文档、支持入口放到更容易被看到的位置。"], ["长期展示", "适合稳定服务、工具品牌和 API 周边服务做持续露出，而不是只靠一次公告。"]] as const;
const slots = [["全站顶部横幅", "云服务器、监控、开发者工具、域名、支付、算力、API 周边服务", "可关闭通知条，适合短期活动、品牌入口或重要更新。"], ["赞助商页旗舰合作位", "AI 周边服务、开发者基础设施、工具类品牌、长期合作公告", "独立赞助商页面的大幅横向展示位。"], ["赞助商页品牌展示区", "IP 纯净度检测、云服务器、监控、支付、域名、网络与账号安全工具", "独立赞助商页面的品牌卡片，集中展示服务简介与入口。"], ["中转 API 频道赞助位", "API Gateway、中转站、模型路由平台、公开可核验的优惠码", "频道页顶部或列表附近的横幅 / 图文卡片。"], ["官方 API 合作位", "模型 API、Token Plan、开发者工具、统一接口、模型路由相关服务", "官方 API 页面中的开发者向展示位。"]] as const;
const specs = [["主横幅图", "16:5，推荐 1600 × 500 px，最低 1200 × 375 px。"], ["文件格式", "PNG、JPG 或 WebP，建议小于 500 KB，背景不要透明。"], ["安全区", "关键 Logo 和文字放在中间 80% 区域，四周至少留 48 px。"], ["图片文字", "只放品牌名、短口号或活动关键词，详细说明放卡片字段。"], ["落地页", "提供可公开访问的官网、活动页或文档页。"]] as const;

export default function CommercialPage() {
  return <div className="priceai-page"><main className="priceai-marketing"><section className="priceai-marketing-hero"><p>赞助位合作</p><h1>把你的服务展示给正在比较 AI 价格的人。</h1><div>PriceAI 的赞助位适合展示云服务、开发者工具、网络检测、API Gateway、中转 API 周边服务。<br />可以做品牌露出、优惠活动入口、资料页引流和长期合作展示。</div><nav><a aria-disabled="true">咨询方式准备中</a><a href="#slots">查看投放位置</a></nav></section><section><p className="kicker">赞助能做什么</p><h2>给合适的服务一个清晰入口。</h2><div className="priceai-marketing-grid four">{benefits.map(([title, text]) => <article key={title}><span>⚑</span><h3>{title}</h3><p>{text}</p></article>)}</div></section><section id="slots"><p className="kicker">可投放位置</p><h2>按用户正在看的页面选择位置。</h2><p>不同位置适合不同投放目标：有的适合短活动，有的适合长期曝光，中转 API 相关服务更适合放在频道页、模型页或独立赞助商页面。</p><div className="priceai-marketing-grid three">{slots.map(([title, suitable, display]) => <article className="slot" key={title}><span>⚑</span><h3>{title}</h3><p>正在浏览对应价格与购买路径的用户。</p><b>适合投放</b><p>{suitable}</p><b>展示形式</b><p>{display}</p></article>)}</div></section><section><p className="kicker">素材交付标准</p><h2>一张横幅图，加一组清晰文案。</h2><p>PriceAI 的赞助卡会统一裁切为横向图片位。为了让不同赞助商放在一起时仍然整齐，建议所有投放素材按同一规格提交。</p><div className="priceai-marketing-grid five">{specs.map(([title, text]) => <article key={title}><span>▧</span><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className="priceai-marketing-columns"><article><h3>▤　需要提供的信息</h3><p>一句话说明你的服务解决什么问题，并提供官网或落地页。</p><p>准备短标题、30 到 80 字说明、Logo、品牌图或赞助横幅图。</p><p>说明希望出现的位置、展示周期、是否需要合同或发票。</p></article><article><h3>♧　投放规范</h3><p>赞助位会明确标注为广告或赞助，避免被误解成 PriceAI 推荐。</p><p>赞助不会改变价格、倍率、库存、稳定性、用户反馈和自然排序。</p><p>不接受无法核验或容易误导的表述。</p></article></section><aside className="priceai-marketing-cta"><div><b>◉　投放前建议先准备资料</b><p>把服务简介、落地页、展示周期和素材发来即可。中转 API 相关服务建议一并提供公开价格页、监测页、模型分组和支持入口。</p></div><a aria-disabled="true">投放联系方式准备中</a></aside></main><footer className="priceai-footer"><nav><Link href="/guides">▣　入门指南</Link><Link href="/commercial">♧　商业合作</Link><Link href="/support">♡　支持作者</Link></nav></footer></div>;
}
